# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2022-2024 CYBERTEC PostgreSQL International GmbH <office@cybertec.at>
services:
  # Single page application served via nginx web server
  web_gui:
    image: containers.cybertec.at/cybertec_migrator_${EDITION}/web_gui:${VERSION}
    depends_on:
      core:
        condition: service_started
    environment:
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL:-}
    volumes:
      - ./volumes/web_gui/nginx/htpasswd:/etc/nginx/htpasswd:Z
      - ./volumes/web_gui/nginx/certs:/etc/nginx/certs:Z
    networks:
      - common
    ports:
      - ${EXTERNAL_HTTP_PORT}:8443

  # Migrator core exposed as REST service API
  core:
    image: containers.cybertec.at/cybertec_migrator_${EDITION}/core:${VERSION}
    env_file: .env
    environment:
      # —— Internal database ——
      - CORE_DB_HOST=core_db
      - CORE_DB_PASSWORD=${CORE_DB_PASSWORD}
      - CORE_DB_DATABASE=migrator
      - TNS_ADMIN=/app/config/oracle/network/admin
    depends_on:
      core_db:
        condition: service_healthy
    volumes:
      - ./volumes/core/config:/app/config:Z
    networks:
      - common

  # Internal Migrator database
  core_db:
    image: docker.io/postgres:17-alpine3.21
    environment:
      # —— Postgres settings ——
      - POSTGRES_PASSWORD=${CORE_DB_PASSWORD}
    volumes:
      - core_db-data:/var/lib/postgresql/data
      - ./volumes/core_db/initdb.sh:/docker-entrypoint-initdb.d/init-user-db.sh:Z
    healthcheck:
      # Ensures that the database is ready *and* the password is in sync
      test:
        [
          "CMD-SHELL",
          'psql --username=postgres --dbname=migrator --command="ALTER USER postgres WITH PASSWORD ''${CORE_DB_PASSWORD}''"',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - common

volumes:
  core_db-data:

networks:
  common:
