# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2022 CYBERTEC PostgreSQL International GmbH <office@cybertec.at>

version: "3"

services:
  # Single page application served via nginx web server
  web_gui:
    image: docker.io/cybertecpostgresql/cybertec_migrator-web_gui:${VERSION}
    depends_on:
      core:
        condition: service_started
    volumes:
      - ./docker/templates:/etc/nginx/templates
    ports:
      - ${EXTERNAL_HTTP_PORT}:80
    networks:
      - common

  # Migrator core exposed as REST service API
  core:
    image: docker.io/cybertecpostgresql/cybertec_migrator-core:${VERSION}
    environment:
      # —— Internal database ——
      - CORE_DB_HOST=core_db
      - CORE_DB_PASSWORD=${CORE_DB_PASSWORD}
      - CORE_DB_DATABASE=migrator
      - TNS_ADMIN=/app/config/oracle/network/admin
    depends_on:
      core_db:
        condition: service_healthy
    networks:
      - common
    volumes:
      - ./volumes/core/config:/app/config

  # Internal Migrator database
  core_db:
    image: docker.io/postgres:13-alpine
    environment:
      # —— Postgres settings ——
      - POSTGRES_PASSWORD=${CORE_DB_PASSWORD}
    volumes:
      - core_db-data:/var/lib/postgresql/data
      - ./volumes/core_db/initdb.sh:/docker-entrypoint-initdb.d/init-user-db.sh:Z
    healthcheck:
      # Ensures that the database is ready *and* the password is in sync
      test:
        [
          "CMD-SHELL",
          'psql --username=postgres --dbname=migrator --command="ALTER USER postgres WITH PASSWORD ''${CORE_DB_PASSWORD}''"',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - common

volumes:
  core_db-data:

networks:
  common:
