# Values file for the CYBERTEC-Migrator Helm-Chart

image:
  repository: containers.cybertec.at/cybertec_migrator_professional
  pullPolicy: IfNotPresent
  release: "v3.19.0"

imagePullSecrets:
  - name: "containers.cybertec.at"

migrator:
  ui:
    # Typical NodePort or LoadBalancer | is used for the k8s service type
    serviceType: NodePort
  db:
    init:
      username: postgres
      password: postgres
  storage:
    core_db: 
      size: 5Gi
      storageClass: standard
    core_log: 
      size: 5Gi
      storageClass: standard
    core_config: 
      size: 5Gi
      storageClass: standard

postgres:
  image: docker.io/postgres:13-alpine
