apiVersion: v1
kind: Secret
metadata:
  name: migrator.postgres.core.db
  namespace: {{ .Release.Namespace }}
data:
  username: {{ .Values.migrator.db.init.username }}
  password: {{ .Values.migrator.db.init.password }}

