apiVersion: v1
kind: Service
metadata:
  name: cybertec-migrator
  labels:
    app: cybertec-migrator-app
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-app
  type: {{ .Values.migrator.ui.serviceType }}
